apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-controller
    app.kubernetes.io/part-of: kserve-controller
  name: kserve-controller
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-controller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-controller
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-controller/kserve-controller@sha256:509668551dab9cc4d42c6a7c3528b2a3ec86c9c27220cd3ef4eea302ba9231a2
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
