apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-controller-28
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/modh/kserve-controller@sha256:abe6120a5840e576a6c042ec5ffbd0aff82452d1587e9eeecb9d4d61db74c394
        name: container-image
        resources: {}
status: {}
