apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-controller-28
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/modh/kserve-controller@sha256:17de626e46e3f88b58545548e8767bce638b7ae523a141e768011ffb3d6dc9b0
        name: container-image
        resources: {}
status: {}
