apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-controller
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-controller/kserve-controller@sha256:49bc8823b0a890d840d46700a1a48c696790c9ec1af14ee0904f953e6d98b5f6
        name: container-image
        resources: {}
status: {}
