apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-controller
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-controller/kserve-controller@sha256:5a7211dece40bdfdcf3a83ce34d859d54cb232b840eb02be47cb8205c8bbe1ab
        name: container-image
        resources: {}
status: {}
