apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-controller-28
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-controller-28
    app.kubernetes.io/part-of: kserve-controller
  name: kserve-controller-28
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-controller-28
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-controller-28
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-controller/kserve-controller-28@sha256:b4906a0181db5d884964e2e926f621cf6c439c537166f607dae4052fad952930
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
