apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-controller-28
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-controller-28
    app.kubernetes.io/part-of: kserve-controller
  name: kserve-controller-28
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-controller-28
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-controller-28
    spec:
      containers:
      - image: quay.io/modh/kserve-controller@sha256:17de626e46e3f88b58545548e8767bce638b7ae523a141e768011ffb3d6dc9b0
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
